theme: jekyll-theme-Cayman

# Setup
title: Automation through Accessibility
description: GNOME Terminal automation on Fedora 38 with Wayland
author: Michal Odehnal
baseurl: ""
url: "https://automation_through_a11y.com"
